name: Build
on: [push, pull_request]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: use build from infra repository
      uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/build.yml@main
