name: Build
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build: 
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/build.yml@main
  dev_cd:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/dev_cd.yml@main
    with:
      image-name: snippet-runner
    
