name: "Continuous Deployment to dev"
on:
  push:
    branches:
      - dev
jobs:
  push_to_registry:
    uses: IngSis-Grupo1-2024/snippet-infra/.github/workflows/dev_cd.yml@main
    with:
      image-name: snippet-runner
      env-name: dev